import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { assembleReportData } from "@/lib/reports/data";
import { fmtRange } from "@/lib/dates";
import { formatPosition, formatMinutes } from "@/lib/utils";
import { TASK_CATEGORY_LABELS } from "@/lib/constants";
import { SystemRole } from "@/generated/prisma/enums";

// Public route — no auth. Identified by the report's shareToken only.
export const dynamic = "force-dynamic";

export default async function SharedReportPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  const report = await prisma.report.findUnique({
    where: { shareToken: token },
    include: { client: true, createdBy: { select: { name: true } } },
  });
  if (!report || report.status !== "DELIVERED" || (report.shareExpiresAt && report.shareExpiresAt < new Date())) {
    notFound();
  }

  // Assemble with a system-level viewer scoped to this client only.
  const systemUser = {
    id: "shared-viewer",
    organizationId: report.client.organizationId,
    role: SystemRole.SUPER_ADMIN,
    email: "",
    name: "Shared",
    status: "ACTIVE",
  };
  const spanMs = report.periodEnd.getTime() - report.periodStart.getTime();
  const data = await assembleReportData(
    systemUser as any,
    report.client.id,
    { start: report.periodStart, end: report.periodEnd },
    { start: new Date(report.periodStart.getTime() - spanMs), end: report.periodStart },
    fmtRange(report.periodStart, report.periodEnd),
    "Previous period",
    report.includeApprovedOnly,
  );

  return (
    <div className="mx-auto max-w-3xl space-y-6 px-4 py-8">
      <header className="border-b border-border pb-4 text-center">
        <p className="text-sm font-semibold text-primary">MARKETINCREW · SEO Command Center</p>
        <h1 className="mt-2 text-2xl font-bold">{report.client.name}</h1>
        <h2 className="text-lg text-muted-foreground">{report.title}</h2>
        <p className="mt-1 text-sm text-muted-foreground">{fmtRange(report.periodStart, report.periodEnd)}</p>
      </header>

      {report.executiveSummary && (
        <section>
          <h3 className="mb-2 text-base font-semibold">Executive Summary</h3>
          <p className="whitespace-pre-line text-sm">{report.executiveSummary}</p>
        </section>
      )}

      <section>
        <h3 className="mb-3 text-base font-semibold">Key SEO KPIs</h3>
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
          <Kpi label="Organic Clicks" value={data.gsc.current.clicks.toLocaleString()} />
          <Kpi label="Impressions" value={data.gsc.current.impressions.toLocaleString()} />
          <Kpi label="Sessions" value={data.analytics.current.sessions.toLocaleString()} />
          <Kpi label="Conversions" value={data.analytics.current.conversions.toLocaleString()} />
        </div>
        <p className="mt-2 text-xs text-muted-foreground">Source: Google Search Console &amp; Google Analytics 4</p>
      </section>

      <section>
        <h3 className="mb-3 text-base font-semibold">Keyword Rankings</h3>
        <div className="grid grid-cols-3 gap-3 sm:grid-cols-6">
          <Kpi label="Tracked" value={data.ranking.totals.tracked} />
          <Kpi label="Top 3" value={data.ranking.totals.top3} />
          <Kpi label="Top 10" value={data.ranking.totals.top10} />
          <Kpi label="Top 20" value={data.ranking.totals.top20} />
          <Kpi label="Avg Pos" value={data.ranking.totals.avgPosition ?? "—"} />
          <Kpi label="Improved" value={data.ranking.totals.improved} />
        </div>
      </section>

      <section>
        <h3 className="mb-3 text-base font-semibold">Tasks Completed ({data.completedTasks.length})</h3>
        <ul className="space-y-1 text-sm">
          {data.completedTasks.map((t) => (
            <li key={t.id} className="flex justify-between border-b border-border py-1">
              <span>{t.title}</span>
              <span className="text-muted-foreground">{TASK_CATEGORY_LABELS[t.category as keyof typeof TASK_CATEGORY_LABELS] ?? t.category}</span>
            </li>
          ))}
          {data.completedTasks.length === 0 && <li className="text-sm text-muted-foreground">No tasks completed this period.</li>}
        </ul>
      </section>

      {report.keyWins && <Commentary title="Key Wins" body={report.keyWins} />}
      {report.issuesRisks && <Commentary title="Issues & Risks" body={report.issuesRisks} />}
      {report.recommendations && <Commentary title="Recommendations" body={report.recommendations} />}
      {report.nextMonthPlan && <Commentary title="Next Month's Plan" body={report.nextMonthPlan} />}

      <footer className="border-t border-border pt-4 text-center text-xs text-muted-foreground">
        <p>This report was generated by MarketinCrew SEO Command Center.</p>
        <p className="mt-1">Ranking change = previous − current (positive = improvement). Position 101 = Not in top 100.</p>
      </footer>
    </div>
  );
}

function Kpi({ label, value }: { label: string; value: number | string }) {
  return (
    <div className="rounded-md border border-border p-3 text-center">
      <p className="text-xl font-semibold">{value}</p>
      <p className="text-[11px] text-muted-foreground">{label}</p>
    </div>
  );
}

function Commentary({ title, body }: { title: string; body: string }) {
  return (
    <section>
      <h3 className="mb-2 text-base font-semibold">{title}</h3>
      <p className="whitespace-pre-line text-sm">{body}</p>
    </section>
  );
}
